### ISSUE TITLE
程序运行时没有发包

### ISSUE THREAD

**Issue by fumengze** [0xf4n9x/DaHuaWPMSinitSessionRCE#1]
加了代理发现没有流量，proxifier抓了进程也是没流量发出去

**Comment by fumengze** [comment]
http协议的可以发包，https协议不行

**Comment by 0xf4n9x** [comment]
[v2.0.1](https://github.com/0xf4n9x/DaHuaWPMSinitSessionRCE/releases/tag/v2.0.1)版本已修复该问题。
